locales:
  - es-ES
  - de-DE
  - fr-FR
base_url: https://wooden-fjord.cloudvent.net/
rosey_paths:
  rosey_base_file_path: ./rosey/base.json
  rosey_base_urls_file_path: ./rosey/base.urls.json
  translations_dir_path: ./rosey/translations
  locales_dir_path: ./rosey/locales
smartling:
  enabled: true
  dev_project_id: 403ba8439
  dev_user_identifier: widgoyosxtbfsfonzlcfejabgndxst
  incoming_translations_dir: ./rosey/smartling-translations/
  outgoing_translations_file_path: ./rosey/outgoing-smartling-translations.json
  outgoing_translation_file_uri: /rosey/translations/
visual_editing:
  visual_editor_syncing: true
  display_orphaned_translations: true
  content_directory: ./src/content
  scope_syncing:
    - content_blocks
  excluded_files:
    - config.ts
  translations_object_name: translations
  migrator_settings:
    enabled: false
    components_directory: ./src/components
tagged_body_content_elements:
  - p
  - li
  - h1
  - h2
  - h3
  - h4
  - h5
  - h6
